FROM ubuntu:16.04

RUN apt-get update --fix-missing && apt-get install -y software-properties-common

RUN apt-get install -y language-pack-en-base &&\
    export LC_ALL=en_US.UTF-8 &&\
    export LANG=en_US.UTF-8
RUN LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
                    php7.2 \
                    php7.2-fpm \
                    php7.2-mbstring \
                    php7.2-mysql \
                    php7.2-xml \
                    php7.2-intl \
                    php7.2-gd \
                    php7.2-curl \
                    php7.2-sqlite3 \
                    php7.2-zip \
                    php7.2-memcache \
                    php7.2-ps\
                    php7.2-xdebug
                    
RUN apt-get -y install --fix-missing --no-install-recommends \
                        build-essential\
                        curl\
                        supervisor\
                        git \
                        wget\
                        nginx\
                        mysql-client\
                        memcached\
                        libmemcached-tools\
                        vim

# RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
#     apt-get install -y nodejs && npm update node-sass@latest

# RUN npm install -g  grunt \
#                     grunt-cli\
#                     gulp

RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

RUN rm -rf /var/lib/apt/lists/*